### ISSUE TITLE
[Suggestion] remove scheme-size from blacklisted mods

### ISSUE THREAD

**Issue by Def-Try** [mindustry-antigrief/mindustry-client#129]
It is no longer just increases schematic size. It is QoL mod, if i can call it this way.
Rendering instruments, admin commands(/js), and etc. idk if it will break anyting and it was blacklisted for other reasons, not only "un needed".

**Comment by buthed010203** [comment]
It was blacklisted since it caused a lot of crashing and other issues

**Comment by Def-Try** [comment]
oh. sorry

**Comment by AmyGilhespy** [comment]
I use it too, and have no issues with using it with Foo's client.  @Def-Try, to un-blacklist it, load the Foo's .jar in a jar dex editor and search for the "scheme-size" in a string constant and replace it with something else, I usually replace it with an equal number of 'x's, then Foo's won't recognize it and you can use both.  I don't think hard blacklisting it was the right way to address this, I think it was actually poor dev practice, but whatever.

A related problem is the way Foo's blacklisted it was kinda bad, and scheme-size sometimes gets "stuck on" when installing unmodified Foo's if you just installed Foo's while you already had scheme-size enabled, then you can't disable scheme-size because Foo's takes over the mod config but isn't smart enough to disable it, so in that case you have to uninstall Foo's, remove scheme-size, then reinstall Foo's.  It's really a pain.  That's if you didn't want both at once but Foo's client keeps you from disabling scheme-size.

**Comment by buthed010203** [comment]
The way its blacklisted in the client is the same way mods are blacklisted in vanilla, it's pretty cursed lol

**Comment by AmyGilhespy** [comment]
I'm liking this comment:  "// FINISHME: Make it display a warning or something and maybe disable them the first time? It shouldn't force people to not use mods".  Thanks for revisiting this!

https://github.com/mindustry-antigrief/mindustry-client/blob/138192ff0868227beb26d90de45a12985325a426/core/src/mindustry/mod/Mods.java#L1080

**Comment by buthed010203** [comment]
Either way i removed scheme-size from that list yesterday as it seems to work decently with foos now (granted lots of features exist twice and such but not much can be done about that)
